version: "1"
services:
  boilerplate:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MODULE_NAME: http-imgress
      EGRESS_API_HOST: https://hookb.in/r1YwjDyn7BHzWWJVK8Gq
      HANDLER_PORT: 80
      INPUT_LABEL: "temperature"
      OUTPUT_LABEL: "temp"
      OUTPUT_UNIT: "Celsius"
    ports:
      - 5000:80
